---

- name: Add PHP7 repo
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
  when: ((php.version == "php5.5") or (php.version == "php5.6") or (php.version == "php7.0"))

- name: Install PHP
  become: yes
  apt:
    update_cache: yes
    name: "{{ item }}"
  tags:
    - provision
  with_items:
    - "{{ php.version }}"
    - "{{ php.version }}-common"
    - "{{ php.version }}-fpm"
    - "{{ php.version }}-cli"

- name: Install base PHP modules
  become: yes
  apt:
    name: "{{ item }}"
  tags:
    - provision
  with_items: "{{ php.modules }}"

- name: Install extra PHP packages
  become: yes
  apt:
    name: "{{ item }}"
  tags:
    - provision
  with_items: "{{ php.extras }}"

- name: Install custom FPM service
  include: fpm.yml
  when: php.fpm.user is defined

- name: Install PECL modules
  include: pecl.yml
  when: "{{ php.pecl }}"
