---
# handlers file for php

- name: restart php-fpm
  service:
    name: "{{ php.fpm.bin }}"
    state: restarted
  become: yes

- name: stop php-fpm
  service:
    name: "{{ php.fpm.bin }}"
    state: stopped
  become: yes

- name: start php-fpm
  service:
    name: "{{ php.fpm.bin }}"
    state: started
  become: yes

- name: reload php-fpm
  service:
    name: "{{ php.fpm.bin }}"
    state: reloaded
  become: yes
